services:
#    bgg_bet.example:
#        class: BGG\BetBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  bgg_bet.antispam:
          class: BGG\BetBundle\Antispam\BGGAntispam
          arguments: [@mailer, %locale%, 50] # Tableau d'arguments